from prometheus_fastapi_instrumentator import Instrumentator
from prometheus_client import Counter, Gauge, Histogram, Info

# ── Business metrics ──────────────────────────────────────────────────────────

telemetry_ingest_counter = Counter(
    "factory_twin_telemetry_ingested_total",
    "Total telemetry records successfully ingested",
    ["machine_id"],
)

alerts_counter = Counter(
    "factory_twin_alerts_generated_total",
    "Total alerts generated by the threshold engine",
    ["machine_id", "severity"],
)

# ── Real-time sensor gauges (latest value per machine) ────────────────────────

telemetry_temperature_gauge = Gauge(
    "factory_twin_sensor_temperature_celsius",
    "Latest temperature reading per machine",
    ["machine_id"],
)

telemetry_vibration_gauge = Gauge(
    "factory_twin_sensor_vibration",
    "Latest vibration reading per machine",
    ["machine_id"],
)

telemetry_rpm_gauge = Gauge(
    "factory_twin_sensor_rpm",
    "Latest RPM reading per machine",
    ["machine_id"],
)

telemetry_oil_gauge = Gauge(
    "factory_twin_sensor_oil_level_percent",
    "Latest oil level per machine",
    ["machine_id"],
)

# ── Operational metrics ───────────────────────────────────────────────────────

active_machines_gauge = Gauge(
    "factory_twin_machines_online_total",
    "Number of machines currently in ONLINE status",
)

ditto_sync_errors_counter = Counter(
    "factory_twin_ditto_sync_errors_total",
    "Number of failed Ditto twin sync attempts",
    ["machine_id"],
)

kafka_publish_errors_counter = Counter(
    "factory_twin_kafka_publish_errors_total",
    "Number of failed Kafka publish attempts",
    ["topic"],
)

# ── Ingestion latency histogram ───────────────────────────────────────────────

ingest_duration_histogram = Histogram(
    "factory_twin_ingest_duration_seconds",
    "End-to-end latency of the /telemetry/ingest endpoint",
    buckets=[0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0],
)

# ── App info (useful for Grafana dashboards) ──────────────────────────────────

app_info = Info(
    "factory_twin_app",
    "Factory Twin application metadata",
)
app_info.info({"version": "1.0.0", "env": "production"})


def setup_metrics(app) -> None:
    """Attach Prometheus instrumentation to the FastAPI app."""
    Instrumentator(
        should_group_status_codes=True,
        should_ignore_untemplated=True,
        excluded_handlers=["/metrics", "/health"],
    ).instrument(app).expose(app, endpoint="/metrics")